### ISSUE TITLE
Allow it to work with other services

### ISSUE THREAD

**Issue by gingerbeardman** [inseven/bookmarks#388]
Pinboard follows the delicious API, as do other services.

It would be great if this app could work with those other services.

One app that worked with both: 
- https://aki-null.net/shiori/

**Comment by jbmorley** [comment]
Are there specific services you'd like to see supported?

**Comment by gingerbeardman** [comment]
Good question! The most popular I know of are:

- linkace
- shaarli
- linkding

**Comment by jbmorley** [comment]
Thanks. I'll definitely explore adding these. Are you making regular use of Bookmarks and, if so, is there one that would be valuable to you?

**Comment by gingerbeardman** [comment]
Hi, I do make use of it (as I transition away from Pinboard).

I had to self-sign the macOS app installed through your pkg but otherwise I like it.

I'll file some issues/requests with my thoughts!
