### ISSUE TITLE
Option to show only top N number of tags 

### ISSUE THREAD

**Issue by gingerbeardman** [inseven/bookmarks#389]
I have been using pinboard since 2011, so I have 3000+ tags! (4000+ bookmarks)

So, it would be great if I could hide most of these as I do not use them to navigate but rather to search.

On pinboard website it gives the option of viewing:
- All
- 5
- 10
- 20
- manage
  - this is mostly managed by the tags sidebar but i think it could have it's own view like the pinboard website, see #393 

I think it would also be useful to view tags that have only been used once so I can delete those.

Thanks for this useful app!

**Comment by jbmorley** [comment]
Putting into v1. Feels like this is an important mechanism for getting users started with common tags.

**Comment by jbmorley** [comment]
Bookmarks on macOS and iOS now supports showing the top 5, 10, 15, and 20 tags in the sidebar.
