### ISSUE TITLE
List or "spreadsheet" view

### ISSUE THREAD

**Issue by gingerbeardman** [inseven/bookmarks#390]
I like the icons and images, but I find them less readable than the plain URL.

So, I'd like to suggest a list or "spreadsheet" view.

Pinboard website shows:
- title
- url
- date bookmarked
  - pinboard uses: friendly
  - i prefer: absolute
- edit button
- delete button

Thanks for your consideration.

ps: similar to https://github.com/otaviocc/Pinboarding but more condensed rows

**Comment by jbmorley** [comment]
On second thoughts, re-opening and putting into 'Future'.

**Comment by gingerbeardman** [comment]
Appreciate your response.

What other clients have spreadsheet view? (other than Pinboarding, which I couldn't get to build)

**Comment by jbmorley** [comment]
It looks like SwiftUI has got multi-column tables for iOS as well now. Worth revisiting this.

**Comment by gingerbeardman** [comment]
Fantastic

**Comment by gingerbeardman** [comment]
Continued thanks.

I've been dabbling with SwiftUI, the time seemed right, so I now appreciate first hand how fractured support is across iOS/macOS and versions thereof!

My app is a little menu bar app (can't use MenuBarExtra as I'm still on Monterey! LOL) is a quick method of sending bookmarks to Linkding! It seems a suitably small app to learn a bunch of stuff, but time and opportunity are my enemy so progress is slow.

So far it send whatever I type in and I can summon it through a global hot key (used a package). I need to hook up capturing the current browser URL and Window/Tab title, and hook up all other manner of niceties and generally improve it.

![Screen shot 2023-06-01 at 19 26 04](https://github.com/inseven/bookmarks/assets/49612/1be8770e-a804-48d0-ace8-6b5742bb159e)

**Comment by gingerbeardman** [comment]
Continued thanks!

----

> I've been dabbling with SwiftUI, the time seemed right, so I now appreciate first hand how fractured support is across iOS/macOS and versions thereof!
> 
> My app is a little menu bar app (so I can't use MenuBarExtra as I'm still on Monterey! LOL) is a quick method of sending bookmarks to Linkding! It seems a suitably small app to learn a bunch of stuff, but time and opportunity are my enemy...so progress is slow.
> 
> So far it sends whatever I type into the text areas (thanks to Swift code generated by Postman), and I can summon it through a global hot key (used a package). I still need to hook up capturing the current browser URL and Window/Tab title, and hook up all other manner of niceties and generally improve it. No ChatGT involved so far, though I will try it soon.
> 
> I'm undecided as to whether to have the popover attached to the menu bar, or a more normal window that appears (which is more like [Shiori.app](https://aki-null.net/shiori/) that I've used for years, and have hacked a version with custom API url where I have an API translator to do Pboard <> Linkding translation).
>
> ![Screen shot 2023-06-01 at 19 26 04](https://github.com/inseven/bookmarks/assets/49612/1be8770e-a804-48d0-ace8-6b5742bb159e)
>

**Comment by jbmorley** [comment]
@gingerbeardman I like the look of this! What's your workflow exactly; how do you get bookmarks into it?

**Comment by jbmorley** [comment]
Closing this issue as fixed; table view now available on macOS and iOS. I'll raise some bugs to track additional columns.

**Comment by gingerbeardman** [comment]
If you try Shiori you'll see. 

Basically:
1. Press global hotkey
1. URL and title are auto-filled from frontmost tab/window/browser
1. Tag field has default focus, enter tags by typing
1. Cmd+enter to submit

Very quick, almost zero friction.

**Comment by jbmorley** [comment]
Oh nice. That makes sense. I guess it's using automation for that then? I like the idea of something so frictionless. Out of interest, what browser do you use?

**Comment by gingerbeardman** [comment]
I use Safari 90%, Chrome 5%, Opera 5%

I'm trying to figure out the best way to grab the URL, it's possible to use embedded AppleScript, or ScriptingBridge, but they can't be used in an app on the Mac App Store. I'm exploring using an embedded Automator Workflow to do it, which they do allow in the Mac App Store.
