### ISSUE TITLE
Building from source could be easier

### ISSUE THREAD

**Issue by gingerbeardman** [inseven/bookmarks#391]
From https://github.com/inseven/bookmarks/issues/388#issuecomment-1073242557

I self-signed the macOS app installed through your pkg. 

Why? I preferred to do this as it was easier for me than building (which failed and I did not have time to look into why or even read the docs).

I had done a simple `./scripts/build.sh --release` with no other changes, but it did not build anything. So I just self-signed.

edit: Now I see that I had to set a bunch of env variables. Oops.

**Comment by jbmorley** [comment]
Regarding self-signing the pkg--I'm most of the way through transitioning to using the TestFlight public betas as a way of distributing builds for iOS and macOS (it's a lot easier to have one process for both platforms). Once that's done it should be really easy to get hold of these development builds. If there's a huge demand, I can bring back the signed macOS .app, but as long as TestFlight builds work for people that's going keep things lightweight.
