### ISSUE TITLE
Tag manager view

### ISSUE THREAD

**Issue by gingerbeardman** [inseven/bookmarks#393]
The tags sidebar is OK for managing tags, but a single column makes managing very many tags quite tricky as you can't see many at once.

I think it's own view like the pinboard website would be better for mass tag management.

Thanks for your consideration!

**Comment by gingerbeardman** [comment]
That's correct!

Sorry I couldn't attach screenshots at the time of bug reporting.

**Comment by jbmorley** [comment]
@gingerbeardman And playing around with this one too:
<img width="630" alt="Screenshot 2022-08-16 at 18 11 56" src="https://user-images.githubusercontent.com/220887/184938821-3718631f-d35c-4a2b-ae2e-50ea23bd6356.png">

**Comment by jbmorley** [comment]
This rudimentary tag manager has now landed, but I'm keeping this issue open to add some actual tag management.

**Comment by jbmorley** [comment]
Closing as 'fixed'. Both iOS and macOS have a dedicated tags view that can grow over time.
