### ISSUE TITLE
Invite users to private beta

### ISSUE THREAD

**Issue by jbmorley** [inseven/bookmarks#406]
- [x] @mikerhodes
- [ ] @gingerbeardman

**Comment by DamnedFacts** [comment]
Hi, I'm excited to see someone building a great Pinboard client, and I was hoping to contribute to your development of it either with testing and bug reports, or even pull requests if they'd be accepted for review.

Any chance I could request access to it via TestFlight? If not, I understand I will make do with building the app myself.

**Comment by jbmorley** [comment]
@DamnedFacts I’m excited to hear you’re excited. 😅

I would love all of the above. The code is in a slightly embarrassing and non-trivial transition as I catch up to the latest SwiftUI (which finally seems to make SwiftUI a realistic option for macOS) but you’re welcome to dive in. Give this, it requires iOS 16 or Ventura.

I anticipate I’ll get to the private beta in the next month or two. Until then, I suggest you build locally—it should be sufficient to open the workspace, select your target, and go (the build script is mostly intended for CI). Let me know if you need help getting started, and I’m happy to accept PRs and documentation improvements.

**Comment by gingerbeardman** [comment]
Ventura may prove to be an issue for me, as I do not plan on upgrading immediately if at all as I have work to do that I cannot disrupt.

**Comment by jbmorley** [comment]
Well, it’ll be waiting for you when it’s safe to upgrade. 👌🏻
